name: Publish

on:
  release:
    types: created

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn tsc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com/
      - run: yarn
      - run: yarn tsc
      # Prepend scope to package name
      - run: sed -i 's/"name":\ "/"name":\ "@kidonng\//' package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-github-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10
      - run: yarn
      - run: yarn tsc
      - run: yarn global add pkg
      - run: pkg dist/src/cli.js --out-path build
      - uses: docker://softprops/action-gh-release
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
